CREATE TABLE IF NOT EXISTS `b_task_queue_jobs` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` varchar(1) NOT NULL DEFAULT 'N',
    `TASK` TEXT NOT NULL,
    `PARAMS` LONGTEXT NOT NULL,
    `DATE_CREATE` date DEFAULT '0000-00-00',
    `DATE_UPDATE` date DEFAULT '0000-00-00',
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `b_task_queue_failed_jobs` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TASK` TEXT NOT NULL,
    `PARAMS` LONGTEXT  NOT NULL,
    `EXCEPTION` LONGTEXT  NOT NULL,
    `DATE_CREATE` date DEFAULT '0000-00-00',
    `DATE_UPDATE` date DEFAULT '0000-00-00',
    PRIMARY KEY (`ID`)
);